### ISSUE TITLE
ssl issue

### ISSUE THREAD

**Issue by ghost** [juwul/umqtt_aws_iot#1]
I am tryign to connect NodeMCU ESP8266 with AWS IOT. I followed your guide at https://forum.pycom.io/topic/908/umqtt-aws-iot.

When trying to connect I am getting an following error
```
    File "/lib/simple.py", line 59, in connect
TypeError: extra keyword arguments given
```
I have already tested AWS IOT connection on PC with AWS SDK and it seems to work fine. So issue seems to be with umqtt clinet and ussl. Any help would be appreciated.

**Comment by juwul** [comment]
@agargautam I think it is concerning the step 2 under the header "The Code" in my guide on Pycom forum. 

Can I have a look at your configuration of the SSL for MQTTClient?

**Comment by ghost** [comment]
Below is the sample code. repoducing just the relevent portion. I tried using 'simple.py' from your repository as well as the offical umqtt simple library. Both giving the same error mentioned above.

Required certicates are in '/cert' directory.

```
from simple import MQTTClient
HOST = {my amazon endpoint}
TOPIC = "sensor_data"

connection = MQTTClient(client_id=TOPIC, server=HOST, port=8883, keepalive=10000, ssl=True, ssl_params={"certfile": "/cert/certificate.pem", "keyfile": "/cert/private.pem", "ca_certs": "/cert/aws-iot-rootCA.pem"})

connection.connect()
```

**Comment by juwul** [comment]
@agargautam Is your certificates placed in the right folder? I can see that your `ssl_params` are missing folder `/flash` before the folder you have created for them.

Below are the differences between our calls:

YOURS
`ssl_params={"certfile": "/cert/certificate.pem", "keyfile": "/cert/private.pem", "ca_certs": "/cert/aws-iot-rootCA.pem"})`

MINE
`ssl_params={
"certfile":"/flash/cert/cert.pem", 
"keyfile":"/flash/cert/privkey.pem", 
"ca_certs":"/flash/cert/aws-iot-rootCA.ca"
})`

**Comment by kkumar326** [comment]
@agargautam were you able to fix this problem?

**Comment by Sunrise17** [comment]
I am also receiving same error as Error in mqtt connect: [Exception] TypeError: extra keyword arguments given. My settings as shown below, Is there some solution about this error?

MQTT_CLIENT_ID = "23876283476233"
MQTT_HOST = "yourSpecificEndPointHere.iot.eu-west-1.amazonaws.com"
MQTT_PORT = 8883

client = MQTTClient(client_id=MQTT_CLIENT_ID, server=MQTT_HOST, port=MQTT_PORT, keepalive=10000, ssl=True, ssl_params={"certfile":"/flash/cert/deviceCertAndCACert.pem", "keyfile":"/flash/cert/deviceCert.key", "ca_certs":"/flash/cert/root.pem"})
 
(With these 2 certs and key, i am successfully connecting to AWS IoT from MQTT.fx)

**Comment by laGapa** [comment]
Same problem here. I believe i found the answer: https://github.com/micropython/micropython/issues/2781. It looks like we can't use TLS client authentication with ussl.wrap_socket() on ESP8266 ... so we can't use it with AWS IoT mqtt at all :(

**Comment by sp0f** [comment]
Same problem here. I believe i found the answer: https://github.com/micropython/micropython/issues/2781. It looks like we can't use TLS client authentication with ussl.wrap_socket() on ESP8266 ... so we can't use it with AWS IoT mqtt at all :(

**Comment by Sunrise17** [comment]
Is it possible to make TLS connection to AWS IoT with ESP32 using umqtt?

**Comment by Sunrise17** [comment]
@juwul , i continue to get same error on ESP32 while executing the method below;
    self.sock = ussl.wrap_socket(self.sock, **self.ssl_params)

This is the print out of ssl_params;
    {'keyfile': '/flash/cert/deviceCert.key', 'certfile': '/flash/cert/deviceCertAndCACert.pem', 'ca_certs': '/flash/cert/root.pem'}

    Traceback (most recent call last):
      File "main.py", line 224, in <module>
      File "main.py", line 182, in mqtt_connect
      File "/lib/simple.py", line 62, in connect
    TypeError: extra keyword arguments given
    MicroPython v1.9.3-286-gbbb08431 on 2018-02-09; ESP32 module with ESP32

**Comment by janoist1** [comment]
Any news on this? I'm still getting the `TypeError: extra keyword arguments given` error. :((
